set_property SRC_FILE_INFO {cfile:C:/Repositories/ECS-ConvolutionalCodeGenerator/ConvolutionalCodeGenerator/vivado/ConvolutionalCodeGenerator.srcs/constrs_1/new/ccg_constraints.xdc rfile:../../../ConvolutionalCodeGenerator.srcs/constrs_1/new/ccg_constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L16 [get_ports clk]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R18 [get_ports rst]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F20 [get_ports a_out]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H20 [get_ports c]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G15 [get_ports a_in]
